apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-world-server
  labels:
    product: server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: tutum/hello-world
        ports:
          - containerPort: 80
